create table invoices
(
    ID     int auto_increment
        primary key,
    client varchar(40) null,
    amount int         null,
    memo   text        null,
    date   date        null
);

INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 471, 'Dinner', '1998-12-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 860, 'Dinner', '2017-05-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 819, 'Dinner', '2008-01-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 609, 'Dinner', '1982-01-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 646, 'Dinner', '1982-07-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 77, 'Dinner', '1996-06-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 376, 'Dinner', '1977-04-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 424, 'Dinner', '1980-11-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 543, 'Dinner', '1970-05-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 507, 'Dinner', '1994-07-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 157, 'Dinner', '2000-03-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 929, 'Dinner', '1994-12-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 447, 'Dinner', '1986-01-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 767, 'Dinner', '2003-11-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 844, 'Dinner', '1980-04-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 404, 'Dinner', '2018-01-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 469, 'Dinner', '2013-04-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 430, 'Dinner', '1995-09-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 919, 'Dinner', '1970-01-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 170, 'Dinner', '2015-03-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 247, 'Dinner', '1989-05-22');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 874, 'Dinner', '2017-11-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 711, 'Dinner', '1980-03-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 623, 'Dinner', '1990-06-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 518, 'Dinner', '2006-06-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 394, 'Dinner', '1991-07-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 476, 'Dinner', '2017-01-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 337, 'Dinner', '2003-05-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 370, 'Dinner', '2003-05-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 656, 'Dinner', '1996-05-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 582, 'Dinner', '1978-03-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 157, 'Dinner', '1979-06-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 539, 'Dinner', '2018-06-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 823, 'Dinner', '2011-11-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 687, 'Dinner', '2020-05-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 13, 'Dinner', '2010-07-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 968, 'Dinner', '1978-09-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 276, 'Dinner', '1972-12-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 692, 'Dinner', '1974-03-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 391, 'Dinner', '1996-11-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 879, 'Dinner', '2004-09-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 449, 'Dinner', '2007-09-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 405, 'Dinner', '1974-11-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 481, 'Dinner', '1977-01-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 932, 'Dinner', '2004-12-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 895, 'Dinner', '1971-03-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 560, 'Dinner', '1985-03-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 480, 'Dinner', '2019-01-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 4, 'Dinner', '2012-04-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 715, 'Dinner', '1972-04-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 46, 'Dinner', '1990-01-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 577, 'Dinner', '1985-09-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 800, 'Dinner', '2014-02-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 721, 'Dinner', '2012-03-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 613, 'Dinner', '1990-02-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 979, 'Dinner', '2008-12-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 349, 'Dinner', '1994-04-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 150, 'Dinner', '2016-05-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 760, 'Dinner', '1988-10-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 868, 'Dinner', '1974-08-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 51, 'Dinner', '1985-10-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 510, 'Dinner', '1987-11-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 991, 'Dinner', '2000-12-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 787, 'Dinner', '1994-02-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 974, 'Dinner', '1972-01-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 539, 'Dinner', '2016-10-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 398, 'Dinner', '2017-05-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 977, 'Dinner', '1983-12-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 757, 'Dinner', '1974-02-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 403, 'Dinner', '1999-01-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 992, 'Dinner', '1990-02-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 266, 'Dinner', '2000-02-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 571, 'Dinner', '1982-08-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 391, 'Dinner', '1998-07-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 273, 'Dinner', '1983-09-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 408, 'Dinner', '1990-05-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 968, 'Dinner', '2009-01-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 68, 'Dinner', '2014-06-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 668, 'Dinner', '2012-05-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 435, 'Dinner', '1983-02-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 141, 'Dinner', '2007-07-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 143, 'Dinner', '2012-12-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 40, 'Dinner', '2015-08-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 353, 'Dinner', '2004-09-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 378, 'Dinner', '2012-11-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 773, 'Dinner', '2011-12-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 433, 'Dinner', '1995-06-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 710, 'Dinner', '1997-05-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 933, 'Dinner', '1975-03-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 969, 'Dinner', '2005-02-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 758, 'Dinner', '1986-06-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 851, 'Dinner', '1988-07-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 522, 'Dinner', '2012-11-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 615, 'Dinner', '1980-03-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 765, 'Dinner', '1997-10-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 308, 'Dinner', '1974-01-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 639, 'Dinner', '2011-03-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 248, 'Dinner', '2009-10-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 600, 'Dinner', '1970-06-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 834, 'Dinner', '1994-11-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 313, 'Dinner', '1999-03-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 480, 'Dinner', '1989-10-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 234, 'Dinner', '2016-03-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 515, 'Dinner', '1985-06-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 193, 'Dinner', '1996-03-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 31, 'Dinner', '1990-07-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 574, 'Dinner', '1985-02-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 830, 'Dinner', '2005-10-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 56, 'Dinner', '2010-08-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 96, 'Dinner', '1973-01-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 525, 'Dinner', '2000-07-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 213, 'Dinner', '1984-10-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 467, 'Dinner', '1996-02-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 289, 'Dinner', '1989-01-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 558, 'Dinner', '1988-11-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 812, 'Dinner', '2011-09-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 222, 'Dinner', '2005-12-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 26, 'Dinner', '2013-03-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 98, 'Dinner', '1985-11-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 192, 'Dinner', '2001-02-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 683, 'Dinner', '1988-09-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 259, 'Dinner', '1982-11-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 671, 'Dinner', '2008-10-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 504, 'Dinner', '1971-04-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 413, 'Dinner', '1994-08-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 812, 'Dinner', '2016-06-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 39, 'Dinner', '2010-07-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 731, 'Dinner', '1993-12-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 12, 'Dinner', '2016-10-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 16, 'Dinner', '1997-09-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 886, 'Dinner', '1990-12-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 563, 'Dinner', '2004-08-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 342, 'Dinner', '2011-10-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 461, 'Dinner', '2017-03-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 861, 'Dinner', '2005-03-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 819, 'Dinner', '1982-10-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 907, 'Dinner', '1999-06-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 169, 'Dinner', '1972-08-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 730, 'Dinner', '1997-12-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 389, 'Dinner', '2013-02-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 498, 'Dinner', '2005-08-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 471, 'Dinner', '1996-08-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 879, 'Dinner', '1990-07-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 905, 'Dinner', '1988-08-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 14, 'Dinner', '1994-08-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 702, 'Dinner', '1995-06-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 910, 'Dinner', '1972-02-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 446, 'Dinner', '1971-02-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 603, 'Dinner', '1988-11-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 744, 'Dinner', '2020-07-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 514, 'Dinner', '1988-01-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 802, 'Dinner', '1978-04-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 523, 'Dinner', '2017-06-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 595, 'Dinner', '2011-06-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 670, 'Dinner', '2019-08-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 213, 'Dinner', '1994-07-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 142, 'Dinner', '2018-04-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 166, 'Dinner', '1982-07-22');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 471, 'Dinner', '1974-02-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 805, 'Dinner', '1985-12-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 1, 'Dinner', '1989-07-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 732, 'Dinner', '2009-03-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 925, 'Dinner', '1986-04-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 987, 'Dinner', '1990-09-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 478, 'Dinner', '2004-02-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 101, 'Dinner', '2001-01-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 4, 'Dinner', '1988-11-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 656, 'Dinner', '1981-05-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 190, 'Dinner', '2018-10-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 267, 'Dinner', '2013-07-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 822, 'Dinner', '1970-03-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 105, 'Dinner', '2003-10-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 909, 'Dinner', '1988-04-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 993, 'Dinner', '2007-06-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 964, 'Dinner', '1994-04-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 966, 'Dinner', '2010-12-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 416, 'Dinner', '2000-07-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 140, 'Dinner', '1994-06-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 396, 'Dinner', '1971-12-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 228, 'Dinner', '2018-07-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 620, 'Dinner', '2019-10-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 712, 'Dinner', '1997-12-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 551, 'Dinner', '2003-01-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 336, 'Dinner', '1985-06-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 628, 'Dinner', '1998-11-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 185, 'Dinner', '1990-10-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 584, 'Dinner', '1991-12-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 391, 'Dinner', '2015-12-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 752, 'Dinner', '1973-11-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 660, 'Dinner', '2016-03-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 786, 'Dinner', '1984-04-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 707, 'Dinner', '1990-05-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 782, 'Dinner', '1993-03-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 89, 'Dinner', '1995-06-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 265, 'Dinner', '2011-01-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 217, 'Dinner', '2017-03-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 158, 'Dinner', '2016-07-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 124, 'Dinner', '1984-05-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 930, 'Dinner', '1985-06-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 615, 'Dinner', '1995-06-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 199, 'Dinner', '1979-10-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 792, 'Dinner', '1990-02-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 226, 'Dinner', '1995-01-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 997, 'Dinner', '1988-08-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 820, 'Dinner', '1984-08-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 782, 'Dinner', '2013-09-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 146, 'Dinner', '1973-02-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 455, 'Dinner', '2014-02-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 682, 'Dinner', '2013-05-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 137, 'Dinner', '2000-10-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 736, 'Dinner', '1988-01-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 275, 'Dinner', '2005-03-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 210, 'Dinner', '2006-10-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 736, 'Dinner', '1989-09-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 11, 'Dinner', '2015-04-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 728, 'Dinner', '1998-01-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 117, 'Dinner', '2012-09-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 368, 'Dinner', '1998-10-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 817, 'Dinner', '1976-05-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 992, 'Dinner', '2008-10-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 317, 'Dinner', '1971-02-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 413, 'Dinner', '1981-10-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 333, 'Dinner', '2002-06-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 709, 'Dinner', '2000-03-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 570, 'Dinner', '1985-11-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 567, 'Dinner', '2006-03-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 489, 'Dinner', '1980-01-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 936, 'Dinner', '1992-10-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 985, 'Dinner', '1976-06-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 879, 'Dinner', '1994-12-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 487, 'Dinner', '1996-01-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 98, 'Dinner', '2001-11-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 325, 'Dinner', '1971-05-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 188, 'Dinner', '2002-04-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 656, 'Dinner', '2007-11-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 876, 'Dinner', '2019-03-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 974, 'Dinner', '2014-12-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 462, 'Dinner', '1979-12-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 327, 'Dinner', '2011-04-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 707, 'Dinner', '1999-02-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 284, 'Dinner', '2017-07-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 841, 'Dinner', '2002-06-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 718, 'Dinner', '1990-01-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 215, 'Dinner', '1989-12-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 33, 'Dinner', '2008-02-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 647, 'Dinner', '1987-05-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 328, 'Dinner', '2017-01-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 458, 'Dinner', '2013-08-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 74, 'Dinner', '1984-10-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 730, 'Dinner', '1982-07-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 447, 'Dinner', '1974-06-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 158, 'Dinner', '2001-06-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 663, 'Dinner', '1987-04-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 54, 'Dinner', '2011-08-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 168, 'Dinner', '2014-02-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 410, 'Dinner', '2002-05-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 24, 'Dinner', '1975-11-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 8, 'Dinner', '2005-05-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 491, 'Dinner', '2014-02-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 996, 'Dinner', '1970-05-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 739, 'Dinner', '1980-01-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 916, 'Dinner', '1987-08-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 958, 'Dinner', '1990-07-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 26, 'Dinner', '2001-01-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 648, 'Dinner', '1994-08-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 639, 'Dinner', '1990-06-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 661, 'Dinner', '1993-04-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 785, 'Dinner', '2014-04-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 565, 'Dinner', '2001-11-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 421, 'Dinner', '1987-01-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 421, 'Dinner', '1978-09-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 299, 'Dinner', '2017-12-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 783, 'Dinner', '1991-11-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 113, 'Dinner', '1980-06-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 606, 'Dinner', '2018-06-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 980, 'Dinner', '1997-11-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 650, 'Dinner', '1980-08-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 41, 'Dinner', '1991-03-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 68, 'Dinner', '2006-03-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 980, 'Dinner', '1997-08-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 430, 'Dinner', '2003-09-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 572, 'Dinner', '2000-08-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 112, 'Dinner', '2016-04-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 530, 'Dinner', '2006-12-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 763, 'Dinner', '2014-06-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 573, 'Dinner', '2019-06-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 335, 'Dinner', '2017-07-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 68, 'Dinner', '1992-01-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 454, 'Dinner', '2009-12-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 831, 'Dinner', '2014-02-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 375, 'Dinner', '1999-02-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 260, 'Dinner', '2001-01-22');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 622, 'Dinner', '1995-08-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 434, 'Dinner', '1974-08-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 916, 'Dinner', '1996-02-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 110, 'Dinner', '1996-04-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 262, 'Dinner', '1988-04-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 151, 'Dinner', '2015-03-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 228, 'Dinner', '1984-04-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 770, 'Dinner', '1972-05-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 487, 'Dinner', '2012-04-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 501, 'Dinner', '1974-08-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 531, 'Dinner', '2012-10-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 789, 'Dinner', '1978-09-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 56, 'Dinner', '1978-10-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 201, 'Dinner', '1986-11-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 855, 'Dinner', '2009-03-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 106, 'Dinner', '2005-11-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 695, 'Dinner', '1998-06-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 145, 'Dinner', '2006-12-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 397, 'Dinner', '1998-08-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 162, 'Dinner', '1998-08-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 897, 'Dinner', '1998-05-22');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 411, 'Dinner', '1999-06-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 88, 'Dinner', '1978-11-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 457, 'Dinner', '1993-03-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 117, 'Dinner', '2010-07-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 850, 'Dinner', '1972-01-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 787, 'Dinner', '1998-11-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 514, 'Dinner', '1983-05-24');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 417, 'Dinner', '2019-10-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 816, 'Dinner', '1971-09-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 208, 'Dinner', '2018-04-08');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 718, 'Dinner', '1970-12-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 108, 'Dinner', '2000-11-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 436, 'Dinner', '1999-02-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 853, 'Dinner', '1970-09-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 536, 'Dinner', '2000-02-22');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 550, 'Dinner', '1987-12-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 31, 'Dinner', '2015-05-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 619, 'Dinner', '2005-09-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 800, 'Dinner', '2009-10-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 740, 'Dinner', '2004-06-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 411, 'Dinner', '2011-03-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 857, 'Dinner', '1970-03-14');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 620, 'Dinner', '2005-09-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 616, 'Dinner', '2005-08-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 397, 'Dinner', '2002-07-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 632, 'Dinner', '1981-04-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 557, 'Dinner', '1970-07-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 30, 'Dinner', '1998-02-07');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 545, 'Dinner', '1993-06-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 278, 'Dinner', '2001-03-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 513, 'Dinner', '1972-08-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 86, 'Dinner', '2014-10-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 891, 'Dinner', '2012-04-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 143, 'Dinner', '2004-02-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 306, 'Dinner', '2013-07-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 847, 'Dinner', '2011-07-09');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 6, 'Dinner', '2011-02-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 584, 'Dinner', '2013-12-15');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 609, 'Dinner', '2011-04-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 676, 'Dinner', '2015-05-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 574, 'Dinner', '2003-06-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 334, 'Dinner', '1992-03-22');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 214, 'Dinner', '2017-11-25');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 432, 'Dinner', '1988-12-18');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 618, 'Dinner', '2014-09-29');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 351, 'Dinner', '2017-05-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 298, 'Dinner', '1992-01-26');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 120, 'Dinner', '2000-06-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 139, 'Dinner', '2004-03-31');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 314, 'Dinner', '2000-01-28');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 273, 'Dinner', '1986-05-19');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 666, 'Dinner', '1983-02-01');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 835, 'Dinner', '2015-01-23');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 507, 'Dinner', '1976-06-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 789, 'Dinner', '1994-10-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 871, 'Dinner', '1970-12-16');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 395, 'Dinner', '2009-03-04');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 960, 'Dinner', '1977-11-17');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 113, 'Dinner', '1971-07-12');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 557, 'Dinner', '1993-03-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 862, 'Dinner', '1993-01-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 4, 'Dinner', '1977-06-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 899, 'Dinner', '1997-12-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 665, 'Dinner', '2010-05-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Wendys', 947, 'Dinner', '2003-05-03');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Pizza Hut', 352, 'Dinner', '1993-07-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('McDonalds', 847, 'Dinner', '1980-01-11');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Bank of America', 404, 'Dinner', '1996-05-02');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Honeywell', 33, 'Dinner', '2013-12-27');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Google', 149, 'Dinner', '2017-03-21');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Facebook', 73, 'Dinner', '2009-01-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Rackspace', 832, 'Dinner', '1989-08-30');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('DigitalOcean', 684, 'Dinner', '1987-02-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('ConsumerAffairs', 47, 'Dinner', '1977-10-05');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Mailchimp', 596, 'Dinner', '2016-11-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Zazzle', 554, 'Dinner', '2003-02-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Quickbooks', 473, 'Dinner', '1974-08-06');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Square', 634, 'Dinner', '1995-02-13');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Consulting People', 310, 'Dinner', '2014-08-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Accountants Inc', 699, 'Dinner', '1972-11-20');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Landlords LLC', 454, 'Dinner', '1999-05-10');
INSERT INTO demodb.invoices (client, amount, memo, date) VALUES ('Local Liquors', 713, 'Dinner', '1986-08-17');